"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$custom\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$conda\
$python\n \
$line_break\
$os\
$shell\
[ï¡](fg:text) \
"""

palette = "rose-pine-moon"

[palettes.rose-pine-moon]
overlay = '#393552'
surface = '#2a273f'
love = '#eb6f92'
gold = '#f6c177'
# rose = '#ea9a97' # moon
rose = '#d7827e' # dawn
# pine = '#3e8fb0' # moon
pine = '#31748f' # main 
# pine = '#286983' # dawn
foam = '#9ccfd8'
iris = '#c4a7e7'
text = '#e0def4'
hightlight = '#56526e'
subtle = '#908caa'
muted = '#6e6a86'

[shell]
disabled = false
style = "bg:rose fg:text"
format = "[ $indicator ]($style)[î‚´](fg:rose) "
bash_indicator = "î¯Š"
fish_indicator = "ï’‹"
zsh_indicator = "ï’"
powershell_indicator = "î¯‡"
cmd_indicator = "î¯„"

[os]
disabled = false
style = "bg:pine fg:text"
format = "[î‚¶](fg:pine)[ $symbol]($style)"

[directory]
format = "[î‚¶](fg:muted)[$path]($style)[î‚´](fg:muted) "
style = "bg:muted fg:text"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ó°Œ¾"
truncate_to_repo = true

[directory.substitutions]
Documents = "ó°ˆ™"
Downloads = "ï€™ "
Music = "ï€ "
Pictures = "ï€¾ "
# "~" = 'ï€• :'
# "~" = "ï‘­ "
"root" = "î­… "
".config" = "î˜• "
"workspace" = "ï„¡ "
"github" = "îª„ "
"equilone" = "ï‘ƒ "

[fill]
style = "fg:overlay"
symbol = " "

[git_branch]
format = "[î‚¶](fg:overlay)[$symbol $branch]($style)[î‚´](fg:overlay)"
style = "bg:overlay fg:subtle"
symbol = "ï˜"

[git_status]
disabled = false
style = "bg:overlay fg:love"
format = "[$ahead_behind]($style)[$all_status]($style)"
up_to_date = '[ î‚¶](fg:overlay)[\(âœ“\)](bg:overlay fg:iris)[î‚´](fg:overlay)'
untracked = '[ î‚¶](fg:overlay)[?\($count\)](bg:overlay fg:gold)[î‚´](fg:overlay)'
stashed = '[ î‚¶](fg:overlay)[\$](bg:overlay fg:iris)[î‚´](fg:overlay)'
modified = '[ î‚¶](fg:overlay)[!\($count\)](bg:overlay fg:gold)[î‚´](fg:overlay)'
renamed = '[ î‚¶](fg:overlay)[Â»\($count\)](bg:overlay fg:iris)[î‚´](fg:overlay)'
deleted = '[ î‚¶](fg:overlay)[âœ˜\($count\)](style)[î‚´](fg:overlay)'
staged = '[ î‚¶](fg:overlay)[++\($count\)](bg:overlay fg:gold)[î‚´](fg:overlay)'
ahead = '[ î‚¶](fg:overlay)[â‡¡\(${count}\)](bg:overlay fg:foam)[î‚´](fg:overlay)'
diverged = '[ î‚¶](fg:overlay)â‡•[\[](bg:overlay fg:iris)[â‡¡\(${ahead_count}\)](bg:overlay fg:foam)[â‡£\(${behind_count}\)](bg:overlay fg:rose)[\]](bg:overlay fg:iris)[î‚´](fg:overlay)'
behind = '[ î‚¶](fg:overlay)[â‡£\(${count}\)](bg:overlay fg:rose)[î‚´](fg:overlay)'

[time]
disabled = true
format = " [î‚¶](fg:overlay)[ $time ó°´ˆ ]($style)[î‚´](fg:overlay)"
style = "bg:overlay fg:rose"
time_format = "%I:%M%P"
use_12hr = false

[username]
disabled = false
format = "[î‚¶](fg:surface)[î·… $user]($style)[î‚´](fg:surface) "
show_always = true
style_root = "bg:surface fg:rose"
style_user = "bg:surface fg:foam"
aliases = { "chase" = "Equil", "equilone" = "Equil", "root" = "Daddy" }

[line_break]
disabled = false

[custom.chezmoi]
style = "bg:overlay fg:subtle"
format = "[î‚¶](fg:overlay)[$symbol$output]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "ó°£« "
when = ''' [[ $PWD == $XDG_DATA_HOME/chezmoi* ]] '''
command = """chezmoi --version | awk '{print $3}' | tr -d ','"""

# Languages

[c]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜ "

[elixir]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î‰µ "

[elm]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜¬ "

[golang]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜§ "

[haskell]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î· "

[java]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î‰– "

[julia]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î˜¤ "

[nodejs]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = true
symbol = "ó°™ "

[nim]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "ó°†¥ "

[rust]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "î¨ "

[scala]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = "îœ· "

[python]
style = "bg:overlay fg:subtle"
format = "[î‚¶](fg:overlay)[$symbol$version]($style)[î‚´](fg:overlay)"
disabled = false
symbol = 'îœ¼ '

[conda]
style = "bg:overlay fg:subtle"
format = " [î‚¶](fg:overlay)[$symbol$environment]($style)[î‚´](fg:overlay)"
disabled = false
symbol = 'ğŸ…’ '

# Operating Systems

[os.symbols]
Alpaquita = "îª¢ "
Alpine = "ïŒ€ "
AlmaLinux = "ïŒ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
Artix = "ïŒŸ "
CachyOS = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
# Fedora = "ïŒ‹ "
FreeBSD = "ïŒŒ "
Garuda = "ó°›“ "
Gentoo = "ïŒ "
HardenedBSD = "ó°Œ "
Illumos = "ó°ˆ¸ "
Kali = "ïŒ§ "
Linux = "ïŒš "
Mabox = "î¬© "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
Nobara = "ï€ "
OpenBSD = "ó°ˆº "
openSUSE = "ïŒ” "
OracleLinux = "ó°Œ· "
Pop = "ïŒª "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
RockyLinux = "ïŒ« "
Redox = "ó°€˜ "
Solus = "ó° ³ "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Void = "ïŒ® "
Windows = "ó°² "
